exports.b = ["﻿Pour prendre le pouvoir, Key est prête à tout, même à ____",
"Le truc le plus dégueulasse que j’ai vu de ma vie ? ____",
"____ Le nouveau moyen de torture de Squal",
"____ Aïe, ça dérape",
"____, le meilleur moyen de faire foirer une run à Linkorange",
"L’anecdote du jour de tonton Schatton : ____",
"Le peu d’autorité que possède Linko réside dans ____",
"Ce que les admins pensent de nous en secret ? ____",
"____ is a secret to everybody",
"Un jour, Link en aura marre de sauver Hyrule, et il partira ____",
"Le charme secret de Nael est dû à ____",
"Ganonbot a encore crash par la faute de ____",
"____ ? cé koi ce nouvo channel ???",
"La meilleure romance imaginée par des fans ? ____",
"(____) Du travail ? Encore du travail ? ",
"Philippe ! Je sais où tu te caches ! Viens ici que je ____, enculé !",
"Les lavages durent plus longtemps avec ____ !",
"Putain, Naël a encore posté une photo de ____",
"Ehhhh salut tout le monde c’est anarith et on se retrouve pour un nouvel épisode du défi sur ____",
"L’autre jour sur la CB, certains ont eu un débat sur ____",
"J’hésite entre ____ et le couscous",
"____ is/are Trash !",
"Se laver dans son ____",
"Qu’est-ce qui équivaut à 8 Nael sur l’échelle de la douleur ? ____",
"Puis bon j’aime bien Hitler mais je préfère de loin ____",
"Nan ____ c'est un travail de femme et la femme ici c'est moi il me semble",
"Ysto t'as l'air pensif ? Tu penses à ____ ? En vrai ce serait vachement bien",
"Is Twil Gay or ____ ?",
"Entre Key la chienne, Song la cochonne et ____, y'a de quoi faire une animalerie",
"____ est aussi serré qu’un pantalon taille XS sur le roi Zora",
"J’espère que toi et ____ n’aviez aucune attache sentimentale",
"____. Mon coeur me dit non, mon cul me dit owi.",
"Moïse, il a ouvert ____ en deux",
"Moi j'ai pas d'ami, j'ai ____, mais c'est plus un animal de compagnie",
"Is ____ gay or european ?",
"Ce soir, tournoi de Smash ! Le perdant devra ____",
"Tu bouffes ____ ? Je prends la saucisse !",
"Je suis pas nul.le au Tic-Tac-Boom, c’est juste que je ____",
"They’re taking ____ to Isengard !",
"Pour moi ____ ça symbolise plus le symbole",
"Avoir du sexe avec ____ c’est le must !",
"Kenny est mort en/de ____ !",
"Son acuité visuelle est basée sur ____",
"Ce que fait la grande fée à Link pour améliorer ses tenues ? ____",
"On a tous quelque chose en nous de ____",
" ____ n’existe pas mais Linkorange est mieux tkt",
"____ Ce que fait Zelda en attendant Link",
"mon main sur Smash ? ____ ",
"Une crêpe à ____.",
"Je suis confiné chez mon plan cul à cause de ____",
"The Legend of Zelda : ____",
"Suis-je gérontophile si je fantasme sur ____",
"Je veux que tu fasse une parodie du générique de pokémon sur ____",
"Il est pas frais ton ____",
"Moi ? J’ai rien à voir avec ____ !",
"Oui, c’est moi qui ait sacrifié ____ putain !",
"____ c’est pas qu’un thermostat Kylink !",
"Je pense que ____ c’est un peu too much en terme d’humour noir",
"Par contre, je note que ____ n’a pas les piles incluses",
"____ c’est la vie !",
"Je pense qu’à Auschwitz, il manquait ____ ",
"Vous pouvez être sûr que si Joseph d’Arimathie a pas été trop con, le graal c’est ____",
"Maman, ma basse ne sert pas à ____",
"Je vis avec un frère ayant le QI de ____, c’est pas pour ça que j’en suis un(e)",
"Félicitations, vous avez gagné ____ !",
"Ce soir, au théâtre du petit enculé : ____",
"Oui c’est ça, puis l’avantage de partir en couille c’est que souvent ____",
"J’irai me coucher quand vous m’aurez juré qu’il n’y a pas dans cette forêt d’animal plus dangereux que ____ !",
"Le prochain personnage annoncé dans Smash Bros : ____ !",
"Je fais une TwilCynder ; Genre tu ____.",
"____, ça me semble évident oui !",
"Faut pas ____, ça fait tousser",
"____, à prendre avec des circonflexes",
"Je gueule, je gueule, j’pourrais gueuler dans ____, ce serait pareil !",
"On n’entre pas si facilement en ____",
"Une occasion rêvée pour ____ de prouver sa valeur.",
"Le meilleur remède contre la gueule de bois, c’est ____",
"Si vous êtes plus à l’aise avec les notions concrètes, je peux vous proposer ____",
"____, c’était mieux avant.",
"Dans notre corps, il y a ____",
"Les USA ont été particulièrement traumatisés par ____",
"Je ____ tout ce qui me passe par la main parce que je m’emmerde !",
"Le prochain roi du Gondor sera ____",
"Ce porno à succès a été réalisé par ____",
"Pour savoir si y a du vent, faut ____",
"Tu sais que ton Skyrim est trop moddé quand tu as ____",
"La meilleure façon de faire du sexe ? ____",
"La dernière vanne de Song portait sur ____",
"Les droits de l’Homme, c’est surfait. L’avenir, c’est ____",
"Donnez ____ à cet homme",
"____, ça me paraît aussi évident que Mario qui saute !",
"Je vous aurais suivi, mon frère, mon capitaine, mon ____",
"Ma stratégie militaire quand je joue à Fire Emblem ? C’est simple : ____ !",
"____ ne peut être détruit, par aucun moyen en notre possession.",
"L’autre jour, je me suis posé des questions en tombant sur ____ dans l’historique de ma mère.",
"Le nouveau piège à humains génial de Papyrus : ____",
"Croiser ____ lors d’une soirée échangiste.",
"Le nouveau remède infaillible du docteur Raoult contre le coronavirus : ____",
"Seul ____ pourra mettre fin à l’immortalité de Valéry Giscard D’Estaing",
"Se faire prendre par ____ c’est à la fois douloureux et extrêmement jouissif",
"Je connais peu de choses qui m’excitent autant que ____",
"It's dangerous to go alone, take ____ !",
"Le Seigneur des Anneaux ne serait pas aussi bon sans ____",
"Le très vénérable Arbre Mojo m'a désignée pour être ____ ! J'en suis très honorée !",
"Regarde, le Concile des Fées ! Euh, si tu veux draguer, j'te déconseille l'endroit : c'est rempli de ____.",
"One ne peut pas s'approcher comme ça des ____. Ils sont très craintifs.",
"Tu viens d'atteindre l'âge du Héros de la Légende ! Ce jour se fête : tu dois au moins ____ aujourd'hui !",
"____ est prête. Je l'ai brossée et étrillée pour toi !",
"Il y a eu ____ ! Je me demande qui est le vainqueur !",
"Tu as vu mes habits ? Et mon instrument ? Je dois représenter ____ pour la chevauchée céleste qui a lieu aujourd'hui !",,
"Pour vous le Czar de ce tour est ____",
"La nouvelle théorie de Linko porte sur ____",
"Le niveau de Twil à Smash est comparable à ____",
"La seule chose plus juive que le prénom d’Anarith c’est ____",
"C’est pas l’homme qui prend la mer, c’est la mer qui ____",
"____ a encore déclenché un drama",
"Dire j’ai glissé chef n’excuse pas ____",
"Nael a encore passé plusieurs heures aux toilettes pour ____",
"La seule chose plus weeb que TwilCynder c’est ____",
"La nouvelle théorie de Siphano sur le prochain Zelda parle de ____",
"Siphano a encore eu un drama avec ____",
"Joyeux anniv, je t’offre 10 ans de Twil pour ____",
"En fait, l’antisémitisme de Nael vient de ____",
"La partie confidentielle des archives de la CB renferme ____",
" ________ Tel est le nom de ce chant de connaissance qui vous guidera, Maître.",
"Pour mettre l’ambiance en soirée, rien de tel que ____",
"« Zelda, c'est ma meilleure amie depuis qu'on ____ ! On est fait l'un pour l'autre ! » Gna gna gna !",
"____ fut scellé en ce lieu pendant sept ans.",
"Habituellement, je demande une rançon pour ____, mais pour toi, ce sera gratuit.",
"Mettez-vous un peu à sa place, c'est dur pour elle.  ____ lui rappelle qu'elle n'est pas à la hauteur.",
"Nul doute que ____ nous donnera un avantage considérable contre le Fléau Ganon.",
"J'en étais sûre, ____ ont été conçues pour ________ C'est la seule explication.",
"Mardi matin, l'empereur, sa femme et le p'tit prince, sont venu chez moi pour me serrer ____.",
"Ah, te voilà ! Tu as fait drôlement vite. Tu n'es pas ____ pour rien !",
"Elle a passé la journée entière sur ____. Pas étonnant qu'elle soit épuisée.",
"Vous avez créé ____ ?!",
"Auriez-vous projeté de mettre ____ dans votre parc à dinosaures ? ",
"____ c’est pas comme une brosse à dents, on l’abandonne pas quand elle perd ses poils.",
"Depuis son plus jeune âge, elle passe de longues heures à ____ dans l'eau glacée des sources.",
"Vers l’infini et ____",
"Tu étais un enfant si turbulent ! C'est vrai, tu n'arrêtais pas de ________",
"J'étais heureuse de pouvoir te ____. Très heureuse, même.",
"L'étude des ____ est essentielle à la survie du royaume.",
"____ est un pouvoir sacré, éveillé par la prière.",
"Comme il est docile, à présent ! Moi qui étais si sûre qu'il n'accepterait jamais  ________",
"Tu connais la coutume, bien sûr. Nul ne doit ____.",
"On sera là pour te couvrir, alors transforme-moi ce Ganon en ____ !",
"Le concert approche, mais on dirait que tous les musiciens ____. Tu savais pas ?",
"Je tiens encore secret le problème de ____ aux autres membres du groupe.",
"L'eau est étrangement trouble là où nous ________",
"Faut que j'aille ____ !"]
